#!/usr/bin/env Rscript

# GLIA major revision — Figure 2 rebalanced evidence hierarchy
#
# This script changes the display hierarchy without refitting any model.
# Panel A reads the complete validated 13,926-feature DESeq2 output retained in
# Table S3D. Panels B-D read the validated direct-expression files generated by
# script 82. All plotting, annotation, assembly, and export are performed in R.
#
# Example:
# Rscript scripts/84_plot_glia_R1_figure2_rebalanced.R \
#   --figure-root /path/to/figure2

suppressPackageStartupMessages({
  library(digest)
  library(dplyr)
  library(ggplot2)
  library(ggrepel)
  library(jsonlite)
  library(patchwork)
  library(ragg)
  library(readr)
  library(scales)
  library(systemfonts)
})

options(stringsAsFactors = FALSE)

get_script_path <- function() {
  full_args <- commandArgs(trailingOnly = FALSE)
  file_arg <- grep("^--file=", full_args, value = TRUE)
  if (length(file_arg) != 1L) {
    stop("Unable to resolve the current script path.")
  }
  normalizePath(sub("^--file=", "", file_arg), mustWork = TRUE)
}

get_arg <- function(flag, default = NULL) {
  args <- commandArgs(trailingOnly = TRUE)
  idx <- match(flag, args)
  if (!is.na(idx)) {
    if (idx == length(args)) {
      stop("Missing value after ", flag)
    }
    return(args[[idx + 1L]])
  }
  default
}

assert_true <- function(condition, message) {
  if (!isTRUE(condition)) {
    stop(message, call. = FALSE)
  }
}

sha256_file <- function(path) {
  digest(path, algo = "sha256", file = TRUE, serialize = FALSE)
}

script_path <- get_script_path()
script_dir <- dirname(script_path)
default_figure_root <- normalizePath(file.path(script_dir, ".."), mustWork = TRUE)
figure_root <- normalizePath(
  get_arg("--figure-root", default_figure_root),
  mustWork = TRUE
)

panel_dir <- file.path(figure_root, "data", "panel_ready")
table_dir <- file.path(figure_root, "outputs", "tableS3")
manifest_dir <- file.path(figure_root, "manifests")
output_dir <- file.path(figure_root, "outputs")
dir.create(manifest_dir, recursive = TRUE, showWarnings = FALSE)
dir.create(output_dir, recursive = TRUE, showWarnings = FALSE)

width_mm <- as.numeric(get_arg("--width-mm", "180"))
height_mm <- as.numeric(get_arg("--height-mm", "220"))
dpi <- as.integer(get_arg("--dpi", "300"))
preview_suffix <- get_arg("--preview-suffix", "")
assert_true(is.finite(width_mm) && width_mm > 0, "Invalid --width-mm.")
assert_true(is.finite(height_mm) && height_mm > 0, "Invalid --height-mm.")
assert_true(dpi == 300L, "The submission TIFF is frozen at 300 dpi.")
assert_true(
  grepl("^(_[A-Za-z0-9][A-Za-z0-9._-]*)?$", preview_suffix),
  "Invalid --preview-suffix."
)

input_paths <- c(
  primary_transcriptome = file.path(
    table_dir,
    "TableS3D_primary_transcriptome_deseq2.csv"
  ),
  sample_metadata = file.path(panel_dir, "fig02_sample_metadata.csv"),
  gene_values = file.path(panel_dir, "fig02_gene_values.csv"),
  panel_values = file.path(panel_dir, "fig02_panel_values.csv"),
  panel_effect = file.path(panel_dir, "fig02_panel_effect.csv"),
  panel_loo = file.path(panel_dir, "fig02_panel_loo.csv")
)
missing_inputs <- input_paths[!file.exists(input_paths)]
assert_true(
  length(missing_inputs) == 0L,
  paste("Missing Figure 2 inputs:", paste(basename(missing_inputs), collapse = ", "))
)

primary_de <- read_csv(
  input_paths[["primary_transcriptome"]],
  show_col_types = FALSE
)
sample_metadata <- read_csv(
  input_paths[["sample_metadata"]],
  show_col_types = FALSE
)
gene_values <- read_csv(input_paths[["gene_values"]], show_col_types = FALSE)
panel_values <- read_csv(input_paths[["panel_values"]], show_col_types = FALSE)
panel_effect <- read_csv(input_paths[["panel_effect"]], show_col_types = FALSE)
panel_loo <- read_csv(input_paths[["panel_loo"]], show_col_types = FALSE)

selected_genes <- c("Irf7", "Ifitm3", "Isg15", "Mx1", "Ifit1", "Ifit2", "Ifit3")
stable_fdr_genes <- c("H1f2", "Ttr", "Lst1", "Tnfaip3", "Ccl9")
samples <- c("C1", "C2", "C3", "S1", "S2", "S3")
group_levels <- c("Oxygen control", "Combined exposure")

# Revalidate every numerical anchor used in the revised artwork.
required_de_columns <- c(
  "ensembl_id", "symbol", "base_mean", "log2_fold_change",
  "bh_adjusted_p_value", "bh_fdr_lt_0_05",
  "fdr_lt_0_05_in_all_six_leave_one_animal_out_fits"
)
assert_true(
  all(required_de_columns %in% names(primary_de)),
  "Table S3D lacks columns required for Figure 2A."
)
assert_true(
  nrow(primary_de) == 13926L && !anyDuplicated(primary_de$ensembl_id),
  "Figure 2A requires 13,926 unique DESeq2-tested features."
)
assert_true(
  sum(primary_de$bh_fdr_lt_0_05, na.rm = TRUE) == 40L &&
    sum(primary_de$bh_fdr_lt_0_05 & primary_de$log2_fold_change > 0,
      na.rm = TRUE
    ) == 11L &&
    sum(primary_de$bh_fdr_lt_0_05 & primary_de$log2_fold_change < 0,
      na.rm = TRUE
    ) == 29L,
  "Full-cohort FDR-hit counts differ from the frozen 11-positive/29-negative result."
)
selected_de <- primary_de |> filter(symbol %in% selected_genes)
assert_true(
  nrow(selected_de) == 7L &&
    setequal(selected_de$symbol, selected_genes) &&
    !any(selected_de$bh_fdr_lt_0_05),
  "The seven selected transcripts are incomplete or have changed FDR status."
)
stable_de <- primary_de |>
  filter(fdr_lt_0_05_in_all_six_leave_one_animal_out_fits)
assert_true(
  nrow(stable_de) == 5L && setequal(stable_de$symbol, stable_fdr_genes) &&
    all(stable_de$log2_fold_change < 0),
  "The five same-direction all-omission FDR hits differ from the frozen result."
)
assert_true(
  nrow(sample_metadata) == 6L &&
    identical(sample_metadata$sample, samples) &&
    sum(sample_metadata$cells_retained) == 7371L,
  "Figure 2 sample metadata differ from the six-animal analysis set."
)
assert_true(
  nrow(gene_values) == 42L &&
    setequal(gene_values$gene, selected_genes) &&
    setequal(gene_values$sample, samples) &&
    !anyDuplicated(gene_values[c("gene", "sample")]),
  "Figure 2B requires seven transcripts by six animals."
)
assert_true(
  nrow(panel_values) == 6L && identical(panel_values$sample, samples),
  "Figure 2C requires one value for every animal."
)
assert_true(
  nrow(panel_effect) == 1L &&
    abs(panel_effect$mean_difference[[1L]] - 1.0685736753232482) < 1e-12 &&
    abs(panel_effect$exact_permutation_p[[1L]] - 0.20) < 1e-12,
  "Figure 2C full-cohort effect differs from the verified value."
)
assert_true(
  nrow(panel_loo) == 7L &&
    identical(panel_loo$dropped_animal, c("(none)", samples)) &&
    all(panel_loo$mean_difference > 0),
  "Figure 2D requires the full estimate and all six positive omission estimates."
)

font_match <- systemfonts::match_fonts("Arial")
font_family <- if (nrow(font_match) > 0L && nzchar(font_match$path[[1L]])) {
  "Arial"
} else {
  "Helvetica"
}
if (font_family != "Arial") {
  warning("Arial was not found; using Helvetica.")
}

condition_colors <- c(
  "Oxygen control" = "#0072B2",
  "Combined exposure" = "#D55E00"
)
condition_shapes <- c(
  "Oxygen control" = 16,
  "Combined exposure" = 17
)
neutral_dark <- "#333333"
neutral_mid <- "#6B6B6B"
neutral_light <- "#D5D5D5"
neutral_faint <- "#ECECEC"
neutral_points <- "#BDBDBD"

base_theme <- theme_classic(base_family = font_family, base_size = 8.4) +
  theme(
    text = element_text(color = neutral_dark),
    plot.tag = element_text(size = 11.5, face = "bold", color = "#111111"),
    plot.tag.position = c(0, 1),
    axis.title = element_text(size = 8.1),
    axis.text = element_text(size = 7.5, color = neutral_dark),
    legend.position = "top",
    legend.justification = "left",
    legend.box.just = "left",
    legend.title = element_blank(),
    legend.text = element_text(size = 7.0),
    legend.key.height = grid::unit(3.2, "mm"),
    legend.key.width = grid::unit(4.2, "mm"),
    legend.spacing.x = grid::unit(1.2, "mm"),
    plot.margin = margin(6, 7, 5, 8)
  )

# ---- Panel A: complete transcriptome-wide DESeq2 result -------------------

primary_de_plot <- primary_de |>
  mutate(
    fdr_display = case_when(
      bh_fdr_lt_0_05 & log2_fold_change > 0 ~
        "FDR < 0.05; combined exposure (n = 11)",
      bh_fdr_lt_0_05 & log2_fold_change < 0 ~
        "FDR < 0.05; oxygen control (n = 29)",
      TRUE ~ "Other features (n = 13,886)"
    ),
    fdr_display = factor(
      fdr_display,
      levels = c(
        "Other features (n = 13,886)",
        "FDR < 0.05; oxygen control (n = 29)",
        "FDR < 0.05; combined exposure (n = 11)"
      )
    )
  ) |>
  arrange(bh_fdr_lt_0_05)

fdr_colors <- c(
  "Other features (n = 13,886)" = neutral_points,
  "FDR < 0.05; oxygen control (n = 29)" =
    condition_colors[["Oxygen control"]],
  "FDR < 0.05; combined exposure (n = 11)" =
    condition_colors[["Combined exposure"]]
)

highlight_points <- bind_rows(
  selected_de |>
    mutate(highlight = "Seven selected transcripts"),
  stable_de |>
    mutate(highlight = "FDR threshold retained in all six omissions")
) |>
  mutate(
    highlight = factor(
      highlight,
      levels = c(
        "Seven selected transcripts",
        "FDR threshold retained in all six omissions"
      )
    )
  )

p_a <- ggplot(
  primary_de_plot,
  aes(x = base_mean, y = log2_fold_change)
) +
  geom_hline(
    yintercept = 0,
    color = neutral_mid,
    linetype = "dashed",
    linewidth = 0.45
  ) +
  geom_point(
    aes(color = fdr_display),
    size = 0.75,
    alpha = 0.55,
    stroke = 0
  ) +
  geom_point(
    data = highlight_points,
    aes(shape = highlight),
    color = "#111111",
    fill = "white",
    size = 2.25,
    stroke = 0.65,
    show.legend = c(shape = TRUE, color = FALSE)
  ) +
  geom_text_repel(
    data = selected_de,
    aes(label = symbol),
    family = font_family,
    fontface = "italic",
    size = 2.45,
    color = "#5E3C99",
    seed = 42,
    min.segment.length = 0,
    segment.color = "#8E7CC3",
    segment.size = 0.25,
    box.padding = 0.25,
    point.padding = 0.15,
    max.overlaps = Inf,
    show.legend = FALSE
  ) +
  geom_text_repel(
    data = stable_de,
    aes(label = symbol),
    family = font_family,
    fontface = "italic",
    size = 2.35,
    color = neutral_dark,
    seed = 43,
    min.segment.length = 0,
    segment.color = neutral_mid,
    segment.size = 0.25,
    box.padding = 0.2,
    point.padding = 0.15,
    max.overlaps = Inf,
    show.legend = FALSE
  ) +
  scale_x_log10(
    breaks = c(1, 10, 100, 1000, 10000, 100000),
    labels = label_number(big.mark = ",", accuracy = 1),
    expand = expansion(mult = c(0.02, 0.04))
  ) +
  scale_y_continuous(
    breaks = seq(-4, 6, by = 2),
    limits = c(-5.65, 6.05),
    expand = expansion(mult = c(0, 0))
  ) +
  scale_color_manual(values = fdr_colors, drop = FALSE) +
  scale_shape_manual(
    values = c(
      "Seven selected transcripts" = 23,
      "FDR threshold retained in all six omissions" = 21
    ),
    drop = FALSE
  ) +
  guides(
    color = "none",
    shape = guide_legend(
      order = 1,
      nrow = 1,
      override.aes = list(size = 2.5, color = "#111111", fill = "white")
    )
  ) +
  labs(
    tag = "A",
    x = "Mean normalized count (DESeq2 base mean; log scale)",
    y = paste0(
      "DESeq2 log2 fold change\n",
      "(combined exposure / oxygen control)"
    )
  ) +
  base_theme +
  theme(
    panel.grid.major = element_line(color = neutral_faint, linewidth = 0.35),
    panel.grid.minor = element_blank(),
    legend.position = "inside",
    legend.position.inside = c(0.995, 0.985),
    legend.justification = c("right", "top"),
    legend.box = "vertical",
    legend.background = element_rect(
      fill = scales::alpha("white", 0.90),
      color = NA
    ),
    legend.margin = margin(2, 2, 2, 2)
  )

# ---- Panel B: animal-level expression of the selected transcripts ----------

animal_vertical_offsets <- c(
  C1 = 0.10, C2 = 0, C3 = -0.10,
  S1 = 0.10, S2 = 0, S3 = -0.10
)
animal_order_key <- data.frame(
  sample = samples,
  display_group = factor(
    c(rep("Oxygen control", 3), rep("Combined exposure", 3)),
    levels = group_levels
  ),
  x_key = c(1.20, 2.15, 3.10, 4.20, 5.15, 6.10),
  y_key = rep(7.63, length(samples)),
  stringsAsFactors = FALSE
)
gene_values_plot <- gene_values |>
  mutate(
    display_group = factor(display_group, levels = group_levels),
    y_base = 8 - gene_order,
    group_y = y_base + if_else(
      display_group == "Oxygen control",
      0.15,
      -0.15
    ),
    y_plot = group_y + unname(animal_vertical_offsets[sample])
  )
gene_means <- gene_values_plot |>
  summarise(
    mean_log2_cpm = mean(log2_cpm),
    y_plot = first(group_y),
    .by = c(gene, gene_order, display_group)
  )

p_b <- ggplot(
  gene_values_plot,
  aes(
    x = log2_cpm,
    y = y_plot,
    color = display_group,
    shape = display_group
  )
) +
  geom_hline(
    yintercept = seq_len(7),
    color = neutral_faint,
    linewidth = 0.35
  ) +
  annotate(
    "text",
    x = -0.45,
    y = 7.63,
    label = "Top to bottom:",
    family = font_family,
    size = 2.15,
    color = neutral_mid,
    hjust = 0
  ) +
  geom_point(
    data = animal_order_key,
    aes(
      x = x_key,
      y = y_key,
      color = display_group,
      shape = display_group
    ),
    inherit.aes = FALSE,
    size = 1.25,
    stroke = 0.3,
    show.legend = FALSE
  ) +
  geom_text(
    data = animal_order_key,
    aes(x = x_key + 0.14, y = y_key, label = sample),
    inherit.aes = FALSE,
    family = font_family,
    size = 2.1,
    color = neutral_dark,
    hjust = 0,
    vjust = 0.5
  ) +
  geom_segment(
    data = gene_means,
    aes(
      x = mean_log2_cpm,
      xend = mean_log2_cpm,
      y = y_plot - 0.11,
      yend = y_plot + 0.11,
      color = display_group
    ),
    inherit.aes = FALSE,
    linewidth = 1.0,
    lineend = "round",
    show.legend = FALSE
  ) +
  geom_point(size = 1.8, alpha = 0.9, stroke = 0.35) +
  scale_color_manual(values = condition_colors, breaks = group_levels, drop = FALSE) +
  scale_shape_manual(values = condition_shapes, breaks = group_levels, drop = FALSE) +
  scale_x_continuous(
    breaks = seq(0, 8, by = 2),
    limits = c(-0.55, 8.0),
    expand = expansion(mult = c(0, 0))
  ) +
  scale_y_continuous(
    breaks = 7:1,
    labels = selected_genes,
    limits = c(0.55, 7.78),
    expand = expansion(mult = c(0, 0))
  ) +
  labs(
    tag = "B",
    x = "Animal-level expression (log2 counts per million)",
    y = NULL
  ) +
  base_theme +
  theme(
    axis.text.y = element_text(face = "italic"),
    panel.grid.major.x = element_line(color = neutral_faint, linewidth = 0.35),
    axis.line.y = element_blank(),
    axis.ticks.y = element_blank()
  )

# ---- Panel C: equal-weight seven-transcript values -------------------------

sample_offsets <- c(
  C1 = -0.12, C2 = 0, C3 = 0.12,
  S1 = -0.12, S2 = 0, S3 = 0.12
)
panel_values_plot <- panel_values |>
  mutate(
    display_group = factor(display_group, levels = group_levels),
    group_x = match(display_group, group_levels),
    x_plot = group_x + unname(sample_offsets[sample]),
    label_y = panel_mean_log2_cpm + if_else(
      sample %in% c("C1", "C2"),
      -0.14,
      0.12
    )
  )
panel_group_means <- panel_values_plot |>
  summarise(
    panel_mean = mean(panel_mean_log2_cpm),
    group_x = first(group_x),
    .by = display_group
  )

p_c <- ggplot(
  panel_values_plot,
  aes(
    x = x_plot,
    y = panel_mean_log2_cpm,
    color = display_group,
    shape = display_group
  )
) +
  geom_segment(
    data = panel_group_means,
    aes(
      x = group_x - 0.17,
      xend = group_x + 0.17,
      y = panel_mean,
      yend = panel_mean
    ),
    inherit.aes = FALSE,
    color = neutral_dark,
    linewidth = 0.75,
    lineend = "round"
  ) +
  geom_point(size = 2.6, stroke = 0.45) +
  geom_text(
    aes(y = label_y, label = sample),
    family = font_family,
    size = 2.45,
    color = neutral_dark,
    vjust = 0.5,
    show.legend = FALSE
  ) +
  scale_color_manual(values = condition_colors, guide = "none") +
  scale_shape_manual(values = condition_shapes, guide = "none") +
  scale_x_continuous(
    breaks = c(1, 2),
    labels = c("Oxygen\ncontrol", "Combined\nexposure"),
    limits = c(0.62, 2.38),
    expand = expansion(mult = c(0, 0))
  ) +
  scale_y_continuous(
    breaks = seq(2, 5, by = 0.5),
    limits = c(1.85, 5.02),
    expand = expansion(mult = c(0, 0))
  ) +
  labs(
    tag = "C",
    x = NULL,
    y = paste0(
      "Equal-weight seven-transcript value\n",
      "(mean log2 counts per million)"
    )
  ) +
  base_theme +
  theme(
    legend.position = "none",
    panel.grid.major.y = element_line(color = neutral_faint, linewidth = 0.35),
    axis.line.x = element_blank(),
    axis.ticks.x = element_blank()
  )

# ---- Panel D: one-animal-omission influence analysis -----------------------

loo_order <- c("(none)", samples)
panel_loo_plot <- panel_loo |>
  mutate(
    row_order = match(dropped_animal, loo_order),
    y_plot = 8 - row_order,
    display_label = if_else(
      dropped_animal == "S3",
      paste0(
        sprintf("%.2f", mean_difference),
        " (",
        sprintf("%.0f", attenuation_vs_full_percent),
        "% below full)"
      ),
      sprintf("%.2f", mean_difference)
    )
  )
full_difference <- panel_effect$mean_difference[[1L]]

p_d <- ggplot(panel_loo_plot, aes(x = mean_difference, y = y_plot)) +
  geom_hline(
    yintercept = seq_len(7),
    color = neutral_faint,
    linewidth = 0.35
  ) +
  geom_vline(
    xintercept = 0,
    color = neutral_mid,
    linetype = "dashed",
    linewidth = 0.45
  ) +
  geom_vline(
    xintercept = full_difference,
    color = neutral_light,
    linetype = "dotted",
    linewidth = 0.55
  ) +
  geom_point(
    data = panel_loo_plot |> filter(dropped_animal == "(none)"),
    shape = 18,
    size = 3.0,
    color = neutral_dark
  ) +
  geom_point(
    data = panel_loo_plot |> filter(dropped_animal != "(none)"),
    shape = 21,
    size = 2.4,
    stroke = 0.55,
    color = neutral_dark,
    fill = "white"
  ) +
  geom_text(
    aes(label = display_label),
    family = font_family,
    size = 2.45,
    color = neutral_dark,
    hjust = 0,
    nudge_x = 0.055
  ) +
  scale_x_continuous(
    breaks = seq(0, 2, by = 0.5),
    limits = c(-0.15, 2.0),
    expand = expansion(mult = c(0, 0))
  ) +
  scale_y_continuous(
    breaks = 7:1,
    labels = c(
      "Full cohort",
      "Omit C1", "Omit C2", "Omit C3",
      "Omit S1", "Omit S2", "Omit S3"
    ),
    limits = c(0.55, 7.45),
    expand = expansion(mult = c(0, 0))
  ) +
  labs(
    tag = "D",
    x = paste0(
      "Mean difference in seven-transcript expression\n",
      "(combined exposure − oxygen control)"
    ),
    y = NULL
  ) +
  base_theme +
  theme(
    legend.position = "none",
    panel.grid.major.x = element_line(color = neutral_faint, linewidth = 0.35),
    axis.line.y = element_blank(),
    axis.ticks.y = element_blank()
  )

bottom_row <- p_c + p_d + plot_layout(widths = c(0.86, 1.14))
figure_2 <- p_a / p_b / bottom_row +
  plot_layout(heights = c(1.12, 0.95, 0.92))

# ---- Export and reproducibility records -----------------------------------

base_name <- "Figure2_transcriptome_and_selected_transcripts"
pdf_path <- file.path(output_dir, paste0(base_name, ".pdf"))
tiff_path <- file.path(output_dir, paste0(base_name, ".tiff"))
png_path <- file.path(
  output_dir,
  paste0(base_name, "_preview", preview_suffix, ".png")
)
rds_path <- file.path(output_dir, paste0(base_name, ".rds"))

width_in <- width_mm / 25.4
height_in <- height_mm / 25.4
render_warnings <- character()

capture_render_warnings <- function(expr) {
  withCallingHandlers(
    expr,
    warning = function(w) {
      render_warnings <<- unique(c(render_warnings, conditionMessage(w)))
      invokeRestart("muffleWarning")
    }
  )
}

save_quartz_pdf <- function(plot, filename, width, height, family) {
  assert_true(capabilities("aqua"), "Quartz PDF export requires macOS Aqua support.")
  grDevices::quartz(
    file = filename,
    type = "pdf",
    width = width,
    height = height,
    pointsize = 8,
    family = family,
    bg = "white",
    antialias = TRUE
  )
  on.exit(grDevices::dev.off(), add = TRUE)
  capture_render_warnings(print(plot))
}

save_quartz_pdf(figure_2, pdf_path, width_in, height_in, font_family)

ragg::agg_tiff(
  filename = tiff_path,
  width = width_mm,
  height = height_mm,
  units = "mm",
  pointsize = 8,
  background = "white",
  res = dpi,
  scaling = 1,
  compression = "lzw",
  bitsize = 8
)
capture_render_warnings(print(figure_2))
grDevices::dev.off()

ragg::agg_png(
  filename = png_path,
  width = width_mm,
  height = height_mm,
  units = "mm",
  pointsize = 8,
  background = "white",
  res = dpi,
  scaling = 1
)
capture_render_warnings(print(figure_2))
grDevices::dev.off()

saveRDS(figure_2, rds_path, compress = "xz")

output_paths <- c(
  vector_pdf_master = pdf_path,
  submission_tiff = tiff_path,
  png_preview = png_path,
  plot_object = rds_path
)

warning_path <- file.path(manifest_dir, "fig02_v2_render_warnings.txt")
session_path <- file.path(manifest_dir, "fig02_v2_plot_sessionInfo.txt")
input_manifest_path <- file.path(manifest_dir, "fig02_v2_plot_input_manifest.csv")
output_manifest_path <- file.path(manifest_dir, "fig02_v2_plot_output_manifest.csv")
execution_path <- file.path(manifest_dir, "fig02_v2_plot_execution.json")

writeLines(if (length(render_warnings)) render_warnings else "None", warning_path)
writeLines(capture.output(sessionInfo()), session_path)

input_manifest <- data.frame(
  input = names(input_paths),
  relative_path = vapply(
    input_paths,
    function(path) sub(paste0("^", figure_root, "/"), "", path),
    character(1)
  ),
  sha256 = vapply(input_paths, sha256_file, character(1)),
  stringsAsFactors = FALSE
)
output_manifest <- data.frame(
  output = names(output_paths),
  relative_path = file.path("outputs", basename(output_paths)),
  sha256 = vapply(output_paths, sha256_file, character(1)),
  stringsAsFactors = FALSE
)
write_csv(input_manifest, input_manifest_path)
write_csv(output_manifest, output_manifest_path)

execution_manifest <- list(
  figure = "Figure 2",
  purpose = paste(
    "Transcriptome-wide animal-level results followed by secondary descriptive",
    "expression of seven selected interferon-responsive transcripts"
  ),
  generated_utc = format(Sys.time(), tz = "UTC", usetz = TRUE),
  script = basename(script_path),
  script_sha256 = sha256_file(script_path),
  display_map = "RESULTS_DISPLAY_MAP_V2_20260820.md",
  display_map_sha256 = sha256_file(
    file.path(figure_root, "..", "RESULTS_DISPLAY_MAP_V2_20260820.md")
  ),
  dimensions = list(width_mm = width_mm, height_mm = height_mm),
  preview_suffix = preview_suffix,
  analysis_set_cells = 7371L,
  biological_unit = "animal/library",
  transcriptome_features = 13926L,
  full_cohort_fdr_hits = list(
    total = 40L,
    positive = 11L,
    negative = 29L
  ),
  selected_transcripts = as.list(selected_genes),
  selected_transcript_role = "secondary descriptive analysis",
  submission_raster = list(
    format = "TIFF",
    dpi = dpi,
    compression = "LZW",
    bitsize = 8,
    background = "white"
  ),
  vector_master = list(
    format = "PDF",
    device = "macOS Quartz PDF",
    font_family = font_family,
    fonts_requested_embedded = TRUE
  ),
  random_seed = list(ggrepel_selected = 42L, ggrepel_stable = 43L),
  render_warnings = as.list(render_warnings),
  r_version = R.version.string,
  packages = as.list(c(
    digest = as.character(packageVersion("digest")),
    dplyr = as.character(packageVersion("dplyr")),
    ggplot2 = as.character(packageVersion("ggplot2")),
    ggrepel = as.character(packageVersion("ggrepel")),
    jsonlite = as.character(packageVersion("jsonlite")),
    patchwork = as.character(packageVersion("patchwork")),
    ragg = as.character(packageVersion("ragg")),
    readr = as.character(packageVersion("readr")),
    scales = as.character(packageVersion("scales")),
    systemfonts = as.character(packageVersion("systemfonts"))
  )),
  outputs = split(output_manifest, seq_len(nrow(output_manifest)))
)
write_json(execution_manifest, execution_path, pretty = TRUE, auto_unbox = TRUE)
